# Generated by Django 3.1.3 on 2020-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
